name: Node.js CI

on:
  push:
    branches: [ master, v0.3.0 ]
  pull_request:
    branches: [ master, v0.3.0 ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['12', '14', '15']
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://npm.pkg.github.com/
    - name: Install dependencies with yarn
      run: yarn --frozen-lockfile
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    - name: Run tests with jest
      run: yarn test
    - name: Upload coverage with codecov
      uses: codecov/codecov-action@v1
